session_name: "0"
windows:
  - layout: 0510,155x38,0,0[155x23,0,0,5,155x14,0,24,6]
    options:
      automatic-rename: "off"
    panes:
      - focus: "true"
        shell_command: zsh
      - zsh
    start_directory: /home/chrollo/Documents/Programming/C/GFG_C
    window_name: c
  - focus: "true"
    layout: c724,76x38,0,0,7
    options:
      automatic-rename: "off"
    panes:
      - shell_command:
          - nohup /home/chrollo/Downloads/Remnote &
          - zsh
    start_directory: /home/chrollo
    window_name: zsh
