session_name: "0"
windows:
  - layout: 050b,155x38,0,0[155x23,0,0,3,155x14,0,24,4]
    options:
      automatic-rename: "off"
    panes:
      - focus: "true"
        shell_command: zsh
      - zsh
    start_directory: /home/chrollo/Documents/Programming/Web/TWDB
    window_name: web
  - layout: 0510,155x38,0,0[155x23,0,0,5,155x14,0,24,6]
    options:
      automatic-rename: "off"
    panes:
      - focus: "true"
        shell_command: zsh
      - zsh
    start_directory: /home/chrollo/Documents/Programming/Py
    window_name: Py
  - focus: "true"
    layout: cc45,155x38,0,0,8
    options: {}
    panes:
      - shell_command:
          - zsh
          - nohup /home/chrollo/Downloads/RemNote-1.3.15.AppImage &
    start_directory: /home/chrollo/
    window_name: zsh
