session_name: "0"
windows:
  - layout: 0506,155x38,0,0[155x23,0,0,1,155x14,0,24,2]
    options:
      automatic-rename: "off"
    panes:
      - zsh
      - focus: "true"
        shell_command: zsh
    start_directory: /home/chrollo/Documents/Programming/Web/TWDB
    window_name: web
  - layout: 050b,155x38,0,0[155x23,0,0,3,155x14,0,24,4]
    options:
      automatic-rename: "off"
    panes:
      - zsh
      - focus: "true"
        shell_command: zsh
    start_directory: /home/chrollo/Documents/Programming/Py
    window_name: py
  - layout: 0510,155x38,0,0[155x23,0,0,5,155x14,0,24,6]
    options:
      automatic-rename: "off"
    panes:
      - focus: "true"
        shell_command: zsh
      - zsh
    start_directory: /home/chrollo/Documents/Programming/C/GFG
    window_name: c
  - focus: "true"
    layout: c724,76x38,0,0,7
    options: {}
    panes:
      - shell_command:
          - nohup /home/chrollo/Downloads/RemNote-1.3.15.AppImage &
          - nohup notion-app-enhanced &
          - nohup brave &
          - zsh
    start_directory: /home/chrollo
    window_name: zsh
