# window:
#   padding:
#     x: 0
#     y: 0
# scrolling:
#   history: 10000
# font:
#   normal:
#     family: "Terminus(TTF)"
#     style: Regular
#   bold:
#     family: "Terminus(TTF)"
#     style: Bold
#   italic:
#     family: "Terminus(TTF)"
#     style: Italic
#   size: 12
window:
  dynamic_title: true
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
  #dimensions:
  #  columns: 0
  #  lines: 0

  # Window position (changes require restart)
  #
  # Specified in number of pixels.
  # If the position is not set, the window manager will handle the placement.
  #position:
  #  x: 0
  #  y: 0

  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 2
    y: 3

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: false

  # Window title
  title: Alacritty

  # Window class (Linux/BSD only):
  class:
    # Application instance name
    instance: Alacritty
    # General application class
    general: Alacritty

  # GTK theme variant (Linux/BSD only)
  #
  # Override the variant of the GTK theme. Commonly supported values are `dark` and `light`.
  # Set this to `None` to use the default theme variant.
  gtk_theme_variant: None
# Font configuration
font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular
  #bold:
  #family: JetBrains Mono
  #style:

  # Italic font face
  #italic:
  # Font family
  #
  # If the italic family is not specified, it will fall back to the
  # value specified for the normal font.
  #family: monospace

  # The `style` can be specified to pick a specific face.
  #style: Italic

  # Bold italic font face
  #bold_italic:
  # Font family
  #
  # If the bold italic family is not specified, it will fall back to the
  # value specified for the normal font.
  #family: monospace

  # The `style` can be specified to pick a specific face.
  #style: Bold Italic

  # Point size
  size: 15

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: -1
    y: -1

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0
  # If `true`, bold text is drawn using the bright color variants.
  #
draw_bold_text_with_bright_colors: true

# Colors (Gruvbox dark)
# colors:
#   primary:
#     background: "#282828"
#     foreground: "#A89984"

  #cursor:
  #  text: '0x000000'
  #  cursor: '0xffffff'

  # normal:
  #   black: "#202020"
  #   red: "#734541"
  #   green: "#5b6048"
  #   yellow: "#af865a"
  #   blue: "#535c5c"
  #   magenta: "#775759"
  #   cyan: "#6d715e"
  #   white: "#A89984"

  # Bright colors
  # bright:
  #   black: "#402e2e"
  #   red: "#733a34"
  #   green: "#586039"
  #   yellow: "#8f6840"
  #   blue: "#444b4b"
  #   magenta: "#614445"
  #   cyan: "#585c49"
  #   white: "#b0a390"

  # Indexed Colors
  #
  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  #
  # Example:
  #   `- { index: 16, color: '0xff00ff' }`
  #
  # indexed_colors: []



# gruvbox flat Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0x32302F'
    foreground: '0xd4be98'

  # Normal colors
  normal:
    black:   '0x1D2021'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xd8a657'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    aqua:    '0x89b482'
    white:   '0xd4be98'

  # Bright colors
  bright:
    black:   '0x17191a'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xd8a657'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    aqua:    '0x89b482'
    white:   '0xd4be98'

  indexed_colors:
    - { index: 16, color: '0xe78a4e' }
    - { index: 17, color: '0xc14a4a' }

  
background_opacity: 1.0

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  # Click settings
  #
  # The `double_click` and `triple_click` settings control the time
  # alacritty should wait for accepting multiple clicks as one double
  # or triple click.
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: false

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

# Allow terminal applications to change Alacritty's window title.
window.dynamic_title: true

cursor:
  # Cursor style
  #
  # Values for `style`:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Block

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  unfocused_hollow: true

# Live config reload (changes require restart)
live_config_reload: true
