session_name: vacation
windows:
  - layout: f686,159x48,0,0[159x32,0,0,1,159x15,0,33,2]
    options:
      automatic-rename: 'off'
    panes:
      - zsh
      - focus: 'true'
        shell_command: zsh
    start_directory: /home/param/Repos/mooc/java/
    window_name: java
  - layout: f68b,159x48,0,0[159x32,0,0,3,159x15,0,33,4]
    options:
      automatic-rename: 'off'
    panes:
      - zsh
      - focus: 'true'
        shell_command: zsh
    start_directory: /home/param/Repos/mooc/n2t
    window_name: nand2tetris
  - layout: 7693,159x48,0,0[159x32,0,0,6,159x15,0,33,7]
    options:
      automatic-rename: 'off'
    panes:
      - zsh
      - focus: 'true'
        shell_command: zsh
    start_directory: /home/param/Repos/mooc/c
    window_name: c
  - focus: 'true'
    layout: 7698,159x48,0,0[159x32,0,0,8,159x15,0,33,9]
    options:
      automatic-rename: 'off'
    panes:
      - focus: 'true'
        shell_command: zsh
      - zsh
    start_directory: /home/param/Repos/mooc/A2Z/
    window_name: cpp
